apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- multikueue.yaml

# Patch admissionChecks onto CQ-1 only (set-1 scope)
patches:
- patch: |-
    - op: add
      path: /spec/admissionChecks
      value:
      - ac-set-1
  target:
    kind: ClusterQueue
    name: cq-1
