apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewebhook
  namespace: default
  labels:
    app: kubewebhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubewebhook
  template:
    metadata:
      labels:
        app: kubewebhook
    spec:
      serviceAccount: kubewebhook-sa
      containers:
        - name: kubewebhook
          image: patilchinmay/kubewebhook:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          # resources:
          #   limits:
          #     memory: 200Mi
          #     cpu: 300m
          #   requests:
          #     memory: 200Mi
          #     cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: kubewebhook-tls-secret
