apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kubewebhook
  labels:
    app: kubewebhook
  annotations:
    cert-manager.io/inject-ca-from: default/kubewebhook-serving-cert
webhooks:
  - name: kubewebhook.default.svc
    failurePolicy: Fail
    sideEffects: None
    reinvocationPolicy: IfNeeded
    admissionReviewVersions:
      - "v1"
    clientConfig:
      caBundle: Cg==
      service:
        name: kubewebhook
        namespace: default
        path: "/v1/webhooks/mutating/pod"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
