apiVersion: v1
kind: Service
metadata:
  name: kubewebhook
  namespace: default
  labels:
    app: kubewebhook
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: 8080
  selector:
    app: kubewebhook
