---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: placeholder
  labels:
    managed-by: argocd
    experiment: kustomize-dynamic-namespaces
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: placeholder
  labels:
    managed-by: argocd
    experiment: kustomize-dynamic-namespaces
