apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: my-password
  namespace: default
spec:
  encryptedData:
    password: AgC9xCUBSEmutz/Jq0p9UwvAd1Kpf71viNkXuI18G3tV2Oy31hHBr0h3SnZ6DZ9ZunVKuL6OCBPYDJHrg0RAau2ewtMVqBSMWHeRmfDkS4SXXvwzeiNM49oGrXLn6geYSpsngFEa3LiB9K6nPJ2x4C1LIk3R2MDhVKtT7NLFRk5VUrO7mDVCn5AuSgnKTrNbx26RBWAD9xr1zKm5boOb5O+fQOLrclntgEis3ukA0XHtRwA0232DetB3GZCRCIK/yO6lZRyyKs9mumV0GC6SNG25S4BxRlmQWEtSrX4BTbeE2V5BJLUnLzRbikzPIYNXqAlN1tL21dSqi++NmJi8V+QLGOuemdfPGgbigu1BWiJ3o87sjP+Tntp4aQJQNxEpqauH7TjEGKNwByeZN/3hRYLwkwPdO8cdF+XkDR7RFmh7ejLnFHttWISkf1xLMTXRAkOfGapSaLgFmGsIecvf/BlzwNM7ZKlVs7Z2izxbe/vAd9L/ABA90UG6HrRG+oQ9cfsDvyEb1jf+0iAsTo7zRDp8D5emadrTg9H5Q6KpVZybypBa/JAD/zNTEQkG9HJbWSKgVhG28fvADTkevksG2Xehz9xKAL5nPqzsX7/fddPDCjsx4yWZq8tByErF7O06d1DnOvneCx9qkgZMYVXi3zVEpL4sA+7m+LrFzonN//FgbFPHJ6nR98uQHTcluQJiRRtdDhkKwEm2IAryixFrnqO3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: my-password
      namespace: default

