---
apiVersion: v1
kind: Secret
metadata:
  name: gke-1-secret
  namespace: kueue-system
data:
  kubeconfig: <REDACTED>
---
apiVersion: v1
kind: Secret
metadata:
  name: eks-1-secret
  namespace: kueue-system
data:
  kubeconfig: <REDACTED>
---
apiVersion: v1
kind: Secret
metadata:
  name: onprem-1-secret
  namespace: kueue-system
data:
  kubeconfig: <REDACTED>
