---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: federation-demo
  labels:
    managed-by: argocd
    experiment: argocd-multi-cluster-federation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: federation-demo
  labels:
    managed-by: argocd
    experiment: argocd-multi-cluster-federation
