kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-node-cluster

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
        protocol: tcp # Optional, defaults to tcp

  - role: worker
    labels:
      allocation: on-demand
      node.kubernetes.io/instance-type: kind-node-1
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: ondemand-node-1

  - role: worker
    labels:
      allocation: reserved
      node.kubernetes.io/instance-type: kind-node-1
      reservation-id: reservation-1
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: reservation-1-node-1
          taints:
            - key: reservation-id
              value: reservation-1
              effect: NoSchedule

  - role: worker
    labels:
      allocation: reserved
      node.kubernetes.io/instance-type: kind-node-1
      reservation-id: reservation-1
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: reservation-1-node-2
          taints:
            - key: reservation-id
              value: reservation-1
              effect: NoSchedule

  - role: worker
    labels:
      allocation: reserved
      node.kubernetes.io/instance-type: kind-node-1
      reservation-id: reservation-2
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: reservation-2-node-1
          taints:
            - key: reservation-id
              value: reservation-2
              effect: NoSchedule

  - role: worker
    labels:
      allocation: reserved
      node.kubernetes.io/instance-type: kind-node-1
      reservation-id: reservation-2
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: reservation-2-node-2
          taints:
            - key: reservation-id
              value: reservation-2
              effect: NoSchedule
