apiVersion: batch/v1
kind: Job
metadata:
  name: print-time
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: print-time
          image: bash:latest
          command:
            [
              "/usr/local/bin/bash",
              "-c",
              "for i in {1..60}; do date; sleep 1; done",
            ]
