apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - affinityDemo
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - whoami
              topologyKey: "kubernetes.io/hostname"

      containers:
        - name: whoami
          image: traefik/whoami:latest
          resources:
            requests:
              memory: "32Mi"
              cpu: "64m"
            limits:
              memory: "64Mi"
              cpu: "128m"
          env:
            - name: WHOAMI_PORT_NUMBER
              value: "8765"
          ports:
            - containerPort: 8765
