apiVersion: example.com/v1
kind: ComputeTask
metadata:
  labels:
    app.kubernetes.io/name: computetask
    app.kubernetes.io/managed-by: kustomize
  name: computetask-sample
spec:
  suspend: false
  template:
    # metadata:
    #   labels:
    #     app: computetask-sample
    spec:
      restartPolicy: Never
      containers:
        - name: task
          image: busybox:1.36
          command:
            - sh
            - -c
            - "echo 'hello from computetask' && for i in $(seq 1 30); do echo $i; sleep 1; done"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
